//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AccountingApp
{
    using System;
    using System.Collections.Generic;
    
    public partial class Credentials
    {
        public int CredentialID { get; set; }
        public string Username { get; set; }
        public string Password { get; set; }
        public int AngajatID { get; set; }
        public string Email { get; set; }
    
        public virtual Angajati Angajati { get; set; }
    }
}
